version: "3.9"
services:
  db:
    image: mysql
    expose:
      - "3306"
    volumes:
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - MYSQL_DATABASE=FeedDB
      # - MYSQL_USER=wooseok
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # - MYSQL_PASSWORD=wooseok1234
  server:
    build: .
    links:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app/SnsFeedService.jar"]

    ports: 
      - 8080:8080